<?php
        $this->load->view('layout/Head');
?>
        <body>
<?php
        $this->load->view('layout/Nav');
        $this->load->view('pages/realestate/view/View1');
        $this->load->view('layout/Footer');
        $this->load->view('layout/Js');
?>      
        </body>