<?php
        $this->load->view('layout/Head');
?>
        <body>
<?php
        $this->load->view('layout/Nav');
        $this->load->view('pages/hotel/Searchbar');
        $this->load->view('pages/hotel/Content');
        $this->load->view('layout/Footer');
        $this->load->view('layout/Js');
?>      
        </body>